# Generated by Django 3.0.3 on 2020-07-10 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChristKart', '0002_registration_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
