# Generated by Django 3.0.3 on 2020-07-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChristKart', '0003_auto_20200710_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email_id',
        ),
    ]
